### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by sethmiles**

### CODE REVIEW

**Comment by lzanott2** [comment]
Hi Seth,

I was able to see your comment, about using main and not section last week, but I cannot find it. How do I get to your comment?

Loriana

**Comment by sethmiles** [comment]
That comment was left in canvas under the assignment.

On Thu, Jan 22, 2015 at 12:56 PM, lzanott2 notifications@github.com wrote:

> Hi Seth,
> 
> I was able to see your comment, about using main and not section last
> week, but I cannot find it. How do I get to your comment?
> 
> Loriana
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/lzanott2/Assignment1/pull/1#issuecomment-71087309.

## 

Seth

**Comment by lzanott2** [comment]
Thanks...yeah, I eventually found it in Canvas.

**Comment by lzanott2** [comment]
I emailed you via Canvas, I believe. But a few things to clear up...

1) I completed the week 2 (Assignment 2) work on time. I uploaded my files to Github last Thursday afternoon.
2) My week 2 work is at the same link at Assignment 1 on Github. The dates show when I made the changes.
3) I didn't change the name of my Github file for week 2/ Assignment 2, so I assumed that I would just keep working with the name "Assignment 1."
4) I didn't submit my link to Github on Canvas. For some reason, I was only focused on Github, so apologies.

:-(

**Comment by sethmiles** [comment]
Everything is fine, just submit the link again to canvas for the next
assignment.

Seth

On Tue, Jan 27, 2015 at 12:06 AM, lzanott2 notifications@github.com wrote:

> I emailed you via Canvas, I believe. But a few things to clear up...
> 
> 1) I completed the week 2 (Assignment 2) work on time. I uploaded my files
> to Github last Thursday afternoon.
> 2) My week 2 work is at the same link at Assignment 1 on Github. The dates
> show when I made the changes.
> 3) I didn't change the name of my Github file for week 2/ Assignment 2, so
> I assumed that I would just keep working with the name "Assignment 1."
> 4) I didn't submit my link to Github on Canvas. For some reason, I was
> only focused on Github, so apologies.
> 
> :-(
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/lzanott2/Assignment1/pull/1#issuecomment-71598908.

## 

Seth

**Pull request merged**
